# 语言环境
language: node_js
node_js: stable

# 添加缓存
cache:
  directories:
    - node_modules

# 只检测 blog-source 上的代码提交
branches:
  only:
    - dev

# install hexo & clone theme
before_install:
  - export TZ='Asia/Taipei' # Set Timezone
  - npm install hexo-cli -g
  - git clone -b dev https://github.com/theme-next/hexo-theme-next themes/next

# Start: Build Lifecycle
install:
  - npm install 
  - npm install hexo-generator-search
  - npm install hexo-generator-tag

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "${GH_USER}"
  - git config user.email "${GH_EMAIL}"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle