language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Taipei'

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${GH_USER}"
  - git config user.email "${GH_EMAIL}"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
